version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
    target-branch: "main"
    open-pull-requests-limit: 10
    commit-message:
      prefix: "[npm]"
