name: Auto approve and merge PRs by Dependabot (with your identity)

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  autoapprove:
    name: Auto Approve PRs by Dependabot
    runs-on: ubuntu-latest
    if: ${{ github.actor == 'dependabot[bot]' || github.actor == 'dependabot-preview[bot]' }}
    steps:
      - name: Configure Git Author
        run: |
          git config --global user.name "Your Name"
          git config --global user.email "your.email@example.com"

      - name: Auto approve
        uses: hmarr/auto-approve-action@v4.0.0
        with:
          github-token: ${{ secrets.AUTO_MERGE_TOKEN }}

  automerge:
    name: Auto Merge After Successful Checks
    needs: autoapprove
    runs-on: ubuntu-latest
    if: ${{ github.actor == 'dependabot[bot]' || github.actor == 'dependabot-preview[bot]' }}
    steps:
      - name: Configure Git Author
        run: |
          git config --global user.name "lcsvcn"
          git config --global user.email "6011385+lcsvcn@users.noreply.github.com"

      - name: Auto merge
        uses: pascalgn/automerge-action@v0.16.4
        env:
          GITHUB_TOKEN: ${{ secrets.AUTO_MERGE_TOKEN }}
          MERGE_LABELS: dependencies
